[FS-197] - layout
flow-build/studio-boilerplate pull request #15
Opened 2023-06-01 20:32 UTC by gabrielacsalesc

[tarefa do componente de Layout](https://dsd-fdte.atlassian.net/browse/FS-197?atlOrigin=eyJpIjoiOGVkNmQ5OTFiMTc2NGM4ODlmNTY2NjY5ZDIyZTg3ZjAiLCJwIjoiaiJ9)

ajustei o layout e o styles.

![image](https://github.com/flow-build/studio-boilerplate/assets/75990722/6c2548b3-8781-438a-be4c-c5f6f8549e33)

2023-06-01 21:01 UTC, flipggs requested changes

2023-06-01 21:01 UTC, flipggs commented on src/stories/components/LinkGroup/index.tsx
> +    <S.Container item xs={12} sm={4} md={3} xl={3} style={{ justifyContent: 'center' }}>
Opa, acho que vi um `style` ali hein!!!!
Sugiro colocar o estilo no arquivo de `styles.ts`

2023-06-02 15:48 UTC, BalanFC approved these changes

2023-06-02 17:00 UTC, flipggs requested changes

2023-06-02 17:00 UTC, flipggs commented on src/stories/components/MainContent/styles.ts
> +  min-height: calc(100vh - ${spacing.S269});
Como eu falei em outro comentário, os `spacings` são para espaçamento e não para tamanho, exatamente por esse motivo, se a gente começar a criar `spacing` para todos os tamanhos vamos acabar criando inúmeros espaçamentos e não há necessidade. 
Sugiro colocar o tamanho direto em `rem` mesmo. Pode colocar o valor referente a 250px, vc acabou esquecendo de calcular o `padding-top` de 10px que tem no footer, isso faz ele aumentar 10px na altura dele

2023-06-02 17:00 UTC, flipggs commented on src/theme/spacing.ts
> +  S269: '16.813rem',
Sugiro remover esse espaçamento

2023-06-02 17:33 UTC, flipggs approved these changes

2023-06-02 17:33 UTC, merged