Feat/fs 187 alert modal
flow-build/studio-boilerplate pull request #22
Opened 2023-06-02 20:55 UTC by ThiagoDonas

2023-06-02 20:58 UTC, BalanFC approved these changes

2023-06-02 21:04 UTC, flipggs requested changes

2023-06-02 21:04 UTC, flipggs commented on src/stories/components/AlertModal/styles.ts
> +  color: #0a0a0a;
Sugiro usar o tema para definir a cor. Tente usar as cores da paleta de texto `text.primary`

2023-06-05 13:46 UTC, flipggs requested changes

2023-06-05 13:46 UTC, flipggs commented on src/stories/components/AlertModal/index.tsx
> +  const [open, setOpen] = useState(true);
Sugiro receber a propriedade `open` e não usar ela somente como variável de estado, pois quem irá chamar esse componente pode definir se estará aberto ou fechado.
Pode passar também como propriedade a função `onClose`

2023-06-05 14:03 UTC, elsonfojr-fdte requested changes

2023-06-05 14:03 UTC, elsonfojr-fdte commented on src/stories/components/AlertModal/index.tsx
> +        </S.IconButton>
Sugiro colcoar uma variavel pro titulo do botão (opcional); caso o usuario não passe nada, utilizar o texto OK.

```suggestion
        <S.IconButton onClick={handleCloseModal} variant="outlined">
          {buttonText ?? 'OK'}
        </S.IconButton>
```

2023-06-05 14:46 UTC, flipggs requested changes

2023-06-05 14:48 UTC, ThiagoDonas commented on src/stories/components/AlertModal/types.ts
> +  OnClose: () => void;
Ajustado!!!

2023-06-05 15:29 UTC, elsonfojr-fdte requested changes

2023-06-05 15:35 UTC, elsonfojr-fdte approved these changes

2023-06-05 18:04 UTC, danilopessoa approved these changes

2023-06-05 18:18 UTC, gabrielacsalesc approved these changes

2023-06-06 12:04 UTC, flipggs approved these changes

2023-06-06 12:51 UTC, merged