[FS-185] feat: create menu and add to header
flow-build/studio-boilerplate pull request #23
Opened 2023-06-02 21:39 UTC by gabrielacsalesc

Componente de menu e suas props de menuItems, anchor (left, right, bottom, top), types e logo.

https://www.awesomescreenshot.com/video/17983586?key=54ca088027cf6d97a9960cf0631c9f55

![image](https://github.com/flow-build/studio-boilerplate/assets/75990722/ee0cb2b3-07ca-40f6-8b4d-9abb3bd9cb28)

2023-06-05 13:09 UTC, flipggs requested changes

2023-06-05 13:09 UTC, flipggs commented on src/stories/components/Menu/styles.ts
> +  /* Media Queries */
Sugiro remover esse comentário

2023-06-05 13:09 UTC, flipggs commented on src/stories/components/Menu/useMenu.ts
> +    setTimeout(() => {
Para a Fast precisamos incluir essa lógica com o `setTimeout`. Para o boilerpalte não é necessário. Sugiro remover todo o `setTimeout`

2023-06-05 13:39 UTC, gabrielacsalesc commented on src/stories/components/Header/index.tsx
> +          <S.Wrapper>{menu}</S.Wrapper>
Feito!

2023-06-05 14:54 UTC, danilopessoa commented on src/app/layout.tsx
>  import { Header } from '../stories/components/Header/index';
Padronizar as importações.

2023-06-05 15:24 UTC, elsonfojr-fdte requested changes

2023-06-05 15:24 UTC, elsonfojr-fdte commented on src/stories/components/Menu/styles.ts
> +`;
Remover elemento, não está sendo utilizado

2023-06-05 15:24 UTC, elsonfojr-fdte commented on src/stories/components/Menu/styles.ts
> +`;
A prop logo neste caso não precisa ser um React.ReactNode, pode ser simplesmente um booleano (pois você só está interessada em saber se tem logo ou não).

```suggestion
export const LogoWrapper = styled(Grid, {
  shouldForwardProp: (prop) => !['hasLogo'].includes(prop as boolean)
})<{ hasLogo?: boolean }>`
  width: ${(props) => (props.hasLogo ? 'auto' : '9.375rem')};
  height: ${(props) => (props.hasLogo ? 'auto' : '1.875rem')};
`;
```

2023-06-05 15:24 UTC, elsonfojr-fdte commented on src/stories/components/Menu/styles.ts
> +  }
Sugiro mover isto para o global styles. Caso tenha alguma dúvida de como colocar lá, só me chamar.

2023-06-05 15:24 UTC, elsonfojr-fdte commented on src/app/layout.tsx
> +];
No arquivo mockHeader.ts há o mesmo mock. Utilizar o do arquivo
(Rever outras constantes mockadas, por exemplo, links)

2023-06-05 15:24 UTC, elsonfojr-fdte commented on src/app/layout.tsx
> +    <ImageComponent src="https://img.logoipsum.com/263.svg" alt={'Logo'} width={150} height={30} />
Notei que Logo está sendo reutilizada em mais de um lugar. Acredito que seria mais interessante criar um component chamado Logo para reutilizar e ficar mais fácil de substituir futuramente nos projetos que fizerem fork do boilerplate.

```tsx
const Logo = () => {
  return <ImageComponent src="https://img.logoipsum.com/263.svg" alt={'Logo'} width={150} height={30} />
}
```

2023-06-05 17:22 UTC, gabrielacsalesc commented on src/app/layout.tsx
> +    <ImageComponent src="https://img.logoipsum.com/263.svg" alt={'Logo'} width={150} height={30} />
O logo usa o componente ImageComponent, para caso a imagem estiver quebrada ele retorne um icone de imagem quebrada

2023-06-05 18:46 UTC, elsonfojr-fdte requested changes

2023-06-06 10:49 UTC, elsonfojr-fdte approved these changes

2023-06-06 15:06 UTC, danilopessoa approved these changes

2023-06-06 15:18 UTC, merged