[FS-211] feat: icone badge
flow-build/studio-boilerplate pull request #25
Opened 2023-06-05 18:18 UTC by gabrielacsalesc

Criação do iconLink para receber o badge e fazer navegação quando o icon for clicado

![image](https://github.com/flow-build/studio-boilerplate/assets/75990722/ceda7c97-52ed-4847-80e8-7a3ad40eeb34)

2023-06-05 18:30 UTC, flipggs requested changes

2023-06-05 18:30 UTC, flipggs commented on src/stories/components/IconLink/types.ts
> +  iconSize?: number;
Pelo que pude perceber, essa prop `iconSize` você não está usando no componente. Sugiro remove-la da interface

2023-06-05 18:30 UTC, flipggs commented on src/stories/components/IconLink/styles.ts
> +    background: #d82e23;
Verifique se é possível usar uma cor do tema

2023-06-05 18:31 UTC, gabrielacsalesc commented on src/stories/components/IconLink/types.ts
> +  iconSize?: number;
Feito!

2023-06-06 10:52 UTC, elsonfojr-fdte commented on src/stories/components/Header/index.tsx
> +            {icon && <IconLink badge={1} icon={Person} redirectLink={'/minha-conta'} />}
O valor do badge está setado como 1, acredito que deveria receber tal valor de forma dinâmica.

2023-06-06 17:22 UTC, danilopessoa requested changes

2023-06-06 17:22 UTC, danilopessoa commented on src/stories/components/Header/styles.ts
>    align-items: center;
Atributo duplicado.

2023-06-06 17:55 UTC, flipggs approved these changes

2023-06-06 18:10 UTC, danilopessoa approved these changes

2023-06-06 18:43 UTC, elsonfojr-fdte approved these changes

2023-06-06 18:44 UTC, merged