Feat/fs 215 loading
flow-build/studio-boilerplate pull request #32
Opened 2023-06-06 17:11 UTC by ThiagoDonas

2023-06-06 17:41 UTC, flipggs approved these changes

2023-06-06 18:55 UTC, elsonfojr-fdte requested changes

2023-06-06 18:55 UTC, elsonfojr-fdte commented on src/stories/components/Loading/styles.ts
> +  }
Por correr o risco de ter side effect (como ocorreu em alguns component na FAST), preferível evitar a alteração pela classe -root e criar o component do CircularProgress no style e alterar pela propriedade color. Além de que mantém o padrão que estamos utilizando.

```ts
import MuiCircularProgress from '@mui/material/CircularProgress';
// ...
export const CiruclarProgress = styled(MuiCircularProgress)`
  color: ${({ theme }) => theme.palette.primary.light};
`
```

```suggestion
```

2023-06-07 01:35 UTC, elsonfojr-fdte approved these changes

2023-06-07 01:35 UTC, merged