feat: fs-50 - implement avatar
flow-build/studio-boilerplate pull request #34
Opened 2023-06-06 18:09 UTC by BalanFC

2023-06-06 19:55 UTC, flipggs requested changes

2023-06-06 19:55 UTC, flipggs commented on src/stories/components/Header/index.tsx
> +          {avatar}
Sugiro validar se o `avatar` está preenchido e só exibir caso ele não seja inválido

2023-06-07 13:07 UTC, elsonfojr-fdte requested changes

2023-06-07 13:07 UTC, elsonfojr-fdte commented on src/utils/avatar/index.ts
> +export function getAavatarURL(email: string) {
A letra 'a' em Avaatar está duplicado

```suggestion
export function getAvatarURL(email: string) {
```

2023-06-07 16:38 UTC, flipggs requested changes

2023-06-07 16:38 UTC, flipggs commented on src/stories/components/Header/types.ts
> +  avatar?: ReactNode;
Sugiro trocar o tipo de `ReactNode` para as propriedades do Avatar `AvatarProps`, pois se passar como `ReactNode` quem estiver usando esse componente pode passar qualquer coisa e não necessariamente o avatar. Poderia passar um `h1` por exemplo, e isso não seria bom

2023-06-07 16:38 UTC, flipggs commented on src/stories/components/Menu/types.ts
> +  avatar?: ReactNode;
A mesma lógica se aplica aqui. Sugiro não passar o `ReactNode` e sim as propriedades necessárias para exibir o Avatar

2023-06-07 16:38 UTC, flipggs commented on src/stories/components/Menu/index.tsx
> +                {avatar}
Passando as propriedades nesse ponto precisaria de substituir por
```
  <Avatar alt={userName} src={getAvatarURL(email)} />;
```

Ou algo parecido com isso

2023-06-07 21:52 UTC, flipggs approved these changes

2023-06-07 21:52 UTC, flipggs commented on src/stories/components/Header/types.ts
> +// import { ReactNode } from 'react';
Esqueceu o comentário aqui

2023-06-08 12:19 UTC, merged