Feat/fs 173 input texto
flow-build/studio-boilerplate pull request #4
Opened 2023-05-30 17:22 UTC by ThiagoDonas

Foi feita a criação do inputText padrão

2023-05-30 18:18 UTC, danilopessoa commented on src/stories/components/Forms/InputText/InputText.stories.tsx
> +const Standart = (args: any) => {
@ThiagoDonas não seria melhor trocar o `Standart` por `Standard`?

2023-05-30 18:22 UTC, danilopessoa commented on src/stories/components/Forms/InputText/index.tsx
> +}): JSX.Element => {
@ThiagoDonas aqui você deve usar o `ReactElement` invés do `JSX.Element` que foi depreciado.

2023-05-30 18:35 UTC, flipggs requested changes
Como já haviamos falado, o componente vai ser uma versão mais simplificada. E por esse motivo fiz alguns sugestões. Qualquer coisa pode me chamar

2023-05-30 18:41 UTC, ThiagoDonas commented on src/stories/components/Forms/InputText/InputText.stories.tsx
> +const Standart = (args: any) => {
Sim, já ajustei

2023-05-30 18:42 UTC, ThiagoDonas commented on src/stories/components/Forms/InputText/index.tsx
> +}): JSX.Element => {
Alterado!

2023-05-31 14:03 UTC, flipggs requested changes

2023-05-31 14:32 UTC, flipggs approved these changes

2023-05-31 14:49 UTC, elsonfojr-fdte requested changes

2023-05-31 15:09 UTC, ThiagoDonas commented on src/stories/components/Forms/InputText/styles.ts
> +  max-width: 37.5rem;
Ajustado!!

2023-05-31 15:11 UTC, elsonfojr-fdte approved these changes

2023-05-31 15:12 UTC, merged