[FS-214] [FS-201] pagina coisa
flow-build/studio-boilerplate pull request #41
Opened 2023-06-07 21:33 UTC by gabrielacsalesc

Criação da página de "coisa" 

![image](https://github.com/flow-build/studio-boilerplate/assets/75990722/55f01857-6c2f-4ea8-bad5-60a2db5848a1)

2023-06-07 21:59 UTC, flipggs requested changes

2023-06-07 21:59 UTC, flipggs commented on src/stories/components/MiniCardsCarousel/components/MiniCards/styles.ts
>  export const Img = styled('img')`
Eu não tinha visto no outro PR.
Mas sugiro substituir pelo componente de imagem ou pela imagem do Next

2023-06-07 21:59 UTC, flipggs commented on src/stories/components/MiniCardsCarousel/components/MiniCards/styles.ts
> +  height: 100px;
Sugiro substituir por `rem`

2023-06-08 00:33 UTC, BalanFC commented on src/app/posts/page.tsx
> +import React from 'react';
Acho que não precisa importar isso se não usar nada

2023-06-08 13:03 UTC, merged